services:
  app:
    build: .
    container_name: image-service
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    networks:
      - image-service-net
    
  db: 
    image: postgres:16.3-bullseye
    container_name: postgres
    ports:
      - 5234:5234
    restart: always
    volumes:
      - image-service-data:/var/lib/postgresql/data
    networks:
      - image-service-net
    
volumes:
  image-service-data:

networks:
  image-service-net: