services:
  db: 
    image: postgres:16.3-bullseye
    container_name: postgres
    ports:
      - 5030:5234
    restart: always
    volumes:
      - image-service-data:/var/lib/postgresql/data
    networks:
      - image-service-net
    
volumes:
  image-service-data:

networks:
  image-service-net: